name:                geodude
version:             0.1.0.0
github:              "sam-jay/geodude"
license:             BSD3
author:              "Sam Jayasinghe & Ge Wang"
maintainer:          "sj2564@columbia.edu"
copyright:           "2019 Sam Jayasinghe & Ge Wang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/geodude#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-qq
- bytestring
- text
- containers
- unordered-containers
- QuickCheck
- random
- split
- mtl
- parallel
- deepseq
- directory
- parallel-io

library:
  source-dirs: src

executables:
  geodude-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - geodude

tests:
  geodude-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - geodude
